schemaVersion: 2.1.0
metadata:
  name: roots
components:
  - name: tools
    container:
      env:
        - name: SKIP_TEST_DATABASE
          value: 'true'
        - name: POSTGRES_USER
          value: '{{postgresUser}}'
        - name: POSTGRES_PASSWORD
          value: '{{postgresPassword}}'
        - name: POSTGRES_DB
          value: '{{postgresDb}}'
      endpoints:
        - exposure: public
          name: web
          protocol: https
          targetPort: 3000
      image: quay.io/ludovicus/rails-developer-image:bookworm-latest
      memoryLimit: 2G
      mountSources: true
  - name: postgres
    container:
      endpoints:
        - exposure: none
          name: postgresql
          targetPort: 5432
      env:
        - name: POSTGRES_USER
          value: '{{postgresUser}}'
        - name: POSTGRES_PASSWORD
          value: '{{postgresPassword}}'
        - name: POSTGRES_DB
          value: '{{postgresDb}}'
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      image: postgres:{{postgresVersion}}
      volumeMounts:
        - name: data
          path: /var/lib/postgresql/data
  - name: data
    volume:
      size: 2Gi
variables:
  postgresVersion: "15"
  postgresDb: roots
  postgresUser: roots
  postgresPassword: dasiltuagbkadsh

